# Generated by Django 2.1.2 on 2019-02-09 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowMaster',
            fields=[
                ('id', models.AutoField(max_length=100000, primary_key=True, serialize=False, verbose_name='id')),
                ('followid', models.CharField(max_length=50, null=True, verbose_name='followid')),
                ('userid', models.CharField(max_length=50, null=True, verbose_name='userid')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
        ),
    ]
