# Generated by Django 2.1.2 on 2019-02-10 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMaster',
            fields=[
                ('id', models.AutoField(max_length=100000, primary_key=True, serialize=False, verbose_name='id')),
                ('favoriteid', models.CharField(max_length=50, null=True, verbose_name='favoriteid')),
                ('userid', models.CharField(max_length=50, null=True, verbose_name='userid')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
        ),
    ]
