# Generated by Django 2.1.2 on 2019-02-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMaster',
            fields=[
                ('id', models.AutoField(max_length=100000, primary_key=True, serialize=False, verbose_name='id')),
                ('photo', models.CharField(max_length=100000, verbose_name='photo')),
            ],
        ),
    ]
