# Generated by Django 2.1.2 on 2019-02-07 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomaster',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='photomaster',
            name='userid',
            field=models.CharField(max_length=100000, null=True, verbose_name='userid'),
        ),
        migrations.AlterField(
            model_name='photomaster',
            name='photo',
            field=models.CharField(max_length=100000, null=True, verbose_name='photo'),
        ),
    ]
