# Generated by Django 2.1.2 on 2019-02-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190207_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomaster',
            name='text',
            field=models.TextField(max_length=300, null=True, verbose_name='text'),
        ),
    ]
