# Generated by Django 2.1.2 on 2019-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20190207_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomaster',
            name='photo',
            field=models.CharField(max_length=100000, null=True, verbose_name='photo'),
        ),
    ]
