# Generated by Django 2.1.2 on 2019-02-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('photo', '0005_auto_20190207_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomaster',
            name='Follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.FollowMaster'),
        ),
    ]
