# Generated by Django 2.1.2 on 2019-02-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_photomaster_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomaster',
            name='Follow',
        ),
    ]
