# Generated by Django 2.1.2 on 2019-02-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('photo', '0007_remove_photomaster_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomaster',
            name='follow',
            field=models.ManyToManyField(to='user.FollowMaster', verbose_name='follow'),
        ),
    ]
