# Generated by Django 2.1.2 on 2018-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
            ],
        ),
    ]
