# Generated by Django 2.1.2 on 2019-02-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20190206_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='imgname',
            field=models.CharField(max_length=100, null=True, verbose_name='imgname'),
        ),
    ]
