# Generated by Django 2.1.2 on 2019-02-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_usermaster_imgname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='imgname',
        ),
    ]
