# Generated by Django 2.1.2 on 2019-02-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_auto_20190208_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='userid',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='userid'),
        ),
    ]
